### ISSUE TITLE
对Unicode 编码转换时,能不能同时兼容 \u \U

### ISSUE THREAD

**Issue by llwijvbw123** [qux-bbb/text-utils#1]
对Unicode 编码转换时,能不能同时兼容 \u \U

**Comment by qux-bbb** [comment]
https://github.com/qux-bbb/text-utils/commit/0f55068d86585fb75fb2bb7214ec18c8dd6f9323  
加了，这几天发新版本

**Comment by qux-bbb** [comment]
新版本 v0.1.6 已发布
