### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by jakubklos77** [qux-bbb/text-utils#2]
Hello
love your text-utils addon a lot and using it daily.
I have a few suggestions

1. "HEX" should be changed to "Hex"
The context menu HEX is wrongly spelled (all capitals), it should be "Hex" as it is in the settings. Just some cosmetics

2. Generate UUID
It would be great if you could a new option to generate an UUID or any random unique ID

Thank you very much
Jakub

**Comment by qux-bbb** [comment]
I can change "HEX" to "Hex".  
For the UUID, there's a tool: https://devtoys.app/, If you think it's enough, I will not add this function. If not, I'll try to add it.

**Comment by jakubklos77** [comment]
Thank you for getting back to me.
It would be so much easier to have it inside the VSCode :). I know there are other extensions but I like your way using the context menu better. Random hash / Generate UUID would be nice if you have the time.
Thanks again

**Comment by qux-bbb** [comment]
Can you describe more detail about "Random hash" and "Generate UUID"?  
For example, what type hash? Lower case or Upper case? Only hex char?  
For example, what version UUID? What format? Lower case or Upper case?

**Comment by jakubklos77** [comment]
A simple value for the UUID as
`8bdda653-7e6e-425d-baf8-e50cdba19f1d`
will do. It can be easily used as a hash and GUID too.
It is a ranom 16byte string converted to hex and formatted as UUID.
Thank you

**Comment by qux-bbb** [comment]
I see, please wait for one or two weeks. I have to do something else first.

**Comment by jakubklos77** [comment]
Thank you, will test when ready. No rush.

**Comment by qux-bbb** [comment]
[text-utils-1.1.0.vsix.zip](https://github.com/user-attachments/files/16039071/text-utils-1.1.0.vsix.zip)  
Try this.  You need to unzip and install it by yourself.

**Comment by jakubklos77** [comment]
Works great. Good job and thank you!

**Comment by qux-bbb** [comment]
The commits:  
https://github.com/qux-bbb/text-utils/commit/bf2d1c991fb3f55679b74f51a5b8357d69fc1fb7  
https://github.com/qux-bbb/text-utils/commit/d90b5e65beacd3a5562edee0d84798c61bf6b054  
The release:  
https://github.com/qux-bbb/text-utils/releases/tag/v1.1.0
