### ISSUE TITLE
【功能请求】选定的行顺序逆序

### ISSUE THREAD

**Issue by lartpang** [qux-bbb/text-utils#4]
我有数行文本正好放反了，想逆序恢复一下，目前没有找到比较便捷的方式，看到这个插件功能比较丰富，但是却没有这个功能，不知作者是否可以支持下？

我看了看这个插件的代码，依照现有的借口

https://github.com/qux-bbb/text-utils/blob/6c9f838c5955be6b9afb2bf2c88022196af1fefc/src/sort.ts#L30-L40

似乎实现起来非常简单：

```js
export function reverseLines() {
    let [theString, selectFlag] = getTheString();
    if (!theString) { return; }
    let newlineSymbol = getNewlineSymbol(theString);
    let theLines = theString.split(newlineSymbol);
    
    // 逆序数组
    theLines.reverse();
    
    let resultString = theLines.join(newlineSymbol);
    setTheString(resultString, selectFlag);
}
```

**Comment by qux-bbb** [comment]
我确认一下功能，是这样吗？  
处理前
```
1
3
2
```
处理后
```
2
3
1
```

**Comment by lartpang** [comment]
@qux-bbb 
是的

**Comment by qux-bbb** [comment]
已添加 https://github.com/qux-bbb/text-utils/commit/524f6b336c6922d30dc6a4841635db5f9cf8c998  
可以更新到 v1.2.0 使用
